# Generated by Django 4.0.2 on 2022-02-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inp1', models.IntegerField(max_length=2)),
                ('inp2', models.IntegerField(max_length=2)),
                ('inp3', models.IntegerField(max_length=2)),
                ('inp4', models.IntegerField(max_length=2)),
            ],
        ),
    ]
