# Generated by Django 4.0.2 on 2022-02-28 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_alter_form_inp1_alter_form_inp2_alter_form_inp3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
