# Generated by Django 4.0.2 on 2022-02-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_form_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='inp1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='inp2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='inp3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='inp4',
            field=models.TextField(),
        ),
    ]
