# Generated by Django 4.0.2 on 2022-03-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_alter_form_inp1_alter_form_inp2_alter_form_inp3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
