# Generated by Django 4.0.2 on 2022-03-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
